name: Deploy to Azure

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: deploy-azure
    env:
      # Azure
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZ_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZ_RG: ${{ secrets.AZ_RG }}
      AZ_LOCATION: ${{ secrets.AZ_LOCATION }}
      AZ_PG_LOCATION: ${{ secrets.AZ_PG_LOCATION }}
      AZ_ENV_NAME: ${{ secrets.AZ_ENV_NAME }}
      AZ_ACR_NAME: ${{ secrets.AZ_ACR_NAME }}

      # Public URLs (build-time for frontends; also used at runtime where applicable)
      NEXT_PUBLIC_AUTH_USER_SERVICE: ${{ secrets.NEXT_PUBLIC_AUTH_USER_SERVICE }}
      NEXT_PUBLIC_HOME_PORTFOLIO_SERVICE: ${{ secrets.NEXT_PUBLIC_HOME_PORTFOLIO_SERVICE }}
      NEXT_PUBLIC_MESSAGES_SERVICE: ${{ secrets.NEXT_PUBLIC_MESSAGES_SERVICE }}
      NEXT_PUBLIC_ADMIN_SERVICE: ${{ secrets.NEXT_PUBLIC_ADMIN_SERVICE }}

      NEXT_PUBLIC_USER_API_URL: ${{ secrets.NEXT_PUBLIC_USER_API_URL }}
      NEXT_PUBLIC_PORTFOLIO_API_URL: ${{ secrets.NEXT_PUBLIC_PORTFOLIO_API_URL }}
      NEXT_PUBLIC_MESSAGES_API_URL: ${{ secrets.NEXT_PUBLIC_MESSAGES_API_URL }}
      NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}

      # Backend-to-backend
      USER_SERVICE_URL: ${{ secrets.USER_SERVICE_URL }}
      PORTFOLIO_SERVICE_URL: ${{ secrets.PORTFOLIO_SERVICE_URL }}

      # DB creds (flex servers are discovered; these are used for connection strings)
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

      # CORS
      ALLOWED_ORIGINS: ${{ secrets.ALLOWED_ORIGINS }}

      # Auth + EmailJS
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      AUTH_GITHUB_ID: ${{ secrets.AUTH_GITHUB_ID }}
      AUTH_GITHUB_SECRET: ${{ secrets.AUTH_GITHUB_SECRET }}
      AUTH_GOOGLE_ID: ${{ secrets.AUTH_GOOGLE_ID }}
      AUTH_GOOGLE_SECRET: ${{ secrets.AUTH_GOOGLE_SECRET }}
      AUTH_LINKEDIN_ID: ${{ secrets.AUTH_LINKEDIN_ID }}
      AUTH_LINKEDIN_SECRET: ${{ secrets.AUTH_LINKEDIN_SECRET }}
      AUTH_FACEBOOK_ID: ${{ secrets.AUTH_FACEBOOK_ID }}
      AUTH_FACEBOOK_SECRET: ${{ secrets.AUTH_FACEBOOK_SECRET }}
      NEXT_PUBLIC_EMAILJS_SERVICE_ID: ${{ secrets.NEXT_PUBLIC_EMAILJS_SERVICE_ID }}
      NEXT_PUBLIC_EMAILJS_TEMPLATE_ID: ${{ secrets.NEXT_PUBLIC_EMAILJS_TEMPLATE_ID }}
      NEXT_PUBLIC_EMAILJS_PUBLIC_KEY: ${{ secrets.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY }}
      SERVICE_AUTH_SECRET: ${{ secrets.SERVICE_AUTH_SECRET }}

      # Logging
      LOGGING_LOGLEVEL_DEFAULT: ${{ secrets.LOGGING_LOGLEVEL_DEFAULT }}
      LOGGING_LOGLEVEL_MICROSOFT_ASPNETCORE: ${{ secrets.LOGGING_LOGLEVEL_MICROSOFT_ASPNETCORE }}

      # AI service
      BEST_PORTFOLIO_PROMPT: ${{ secrets.BEST_PORTFOLIO_PROMPT }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      OPENROUTER_MODEL: ${{ secrets.OPENROUTER_MODEL }}
      OPENROUTER_BASE_URL: ${{ secrets.OPENROUTER_BASE_URL }}
      OPENROUTER_PROMPT: ${{ secrets.OPENROUTER_PROMPT }}
      RANKING_LOG_LEVEL: ${{ secrets.RANKING_LOG_LEVEL }}
      LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
      AI_LOG_LEVEL: ${{ secrets.AI_LOG_LEVEL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Deploy all services
        run: |
          set -euo pipefail
          cd scripts/azure
          ./deploy-all.sh

